api:
  image:
    repository: registry.digitalocean.com/flowpay/certificate-signer
    tag: "latest"

  imagePullSecrets:
    - name: flowpay

  ingress:
    className: "nginx-public"
    hosts:
      - host: certificate-signer.flowpay.site
        paths:
          - path: /
            pathType: Prefix

  
  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80

  secretFiles:
    - name: ca-cert
      remoteRefKey: ca-cert
      mountPath: /ca-cert.pem
    - name: ca-key
      remoteRefKey: ca-key
      mountPath: /ca-key.pem

  readiness:
    enabled: true
    endpoint: /ready
  liveness:
    enabled: true
    endpoint: /ready