image:
  repository: registry.digitalocean.com/flowpay/certificate-signer

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  hosts:
    - host: certificate-signer.nebojsa-test.store
 
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80