name: Build docker image

on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        registry: registry.digitalocean.com
        username: ${{ secrets.DO_API_USERNAME }}
        password: ${{ secrets.DO_API_KEY }}

    - name: Build and push
      uses: docker/build-push-action@v4
      with:
        push: true
        build-args: |
            CA_CERT="${{ secrets.CA_CERT }}"
            CA_KEY="${{ secrets.CA_KEY }}""
        tags: registry.digitalocean.com/flowpay/certificate-signer:latest
